In [ ]:
import torch
import numpy
import torch.nn as nn
import torch.nn.functional as F

# wordembedding 以序列建模为例
batch_size = 2

# 单词表大小
max_num_src_words = 8
max_num_tgt_words = 8
model_dim = 8

# 序列的最大长度
max_src_seq_len = 5
max_tgt_seq_len = 5

src_len = torch.Tensor([2, 4]).to(torch.int32)  # 源序列长度
tgt_len = torch.Tensor([4, 3]).to(torch.int32)  # 目标序列长度

# 以单词索引构成的源句子和目标句子，构建batch，并且做了padding，默认值为0
src_seq = torch.cat([torch.unsqueeze(F.pad(torch.randint(1, max_num_src_words, (L,)), (0, max_src_seq_len-L)), 0) for L in src_len])
tgt_seq = torch.cat([torch.unsqueeze(F.pad(torch.randint(1, max_num_tgt_words, (L,)), (0, max_tgt_seq_len-L)), 0) for L in tgt_len])

# 构造word embedding 第零行为padding的embedding
src_embedding_table = nn.Embedding(max_num_src_words+1, model_dim)
tgt_embedding_table = nn.Embedding(max_num_tgt_words+1, model_dim)
src_embedding = src_embedding_table(src_seq) 
tgt_embedding = tgt_embedding_table(tgt_seq)

print(src_embedding_table.weight)
print(src_seq)
print(src_embedding)


Parameter containing:
tensor([[ 1.4789, -0.1258, -0.2743, -1.8418, -2.1465,  2.4762,  0.3513,  0.6852],
        [ 1.5744, -1.4091, -0.6946,  1.5790,  1.0959, -0.7603,  0.6118,  1.0831],
        [-1.2535,  0.0342,  0.8513, -0.0171, -0.3942,  0.2898, -0.7263, -0.6373],
        [-0.7008,  1.4492, -0.2514, -1.3008, -1.5216, -0.2157, -0.2242,  0.4200],
        [ 2.2568, -0.3080, -0.0466,  0.4633, -0.9516, -0.2778, -1.3498, -1.2884],
        [-0.3184,  0.9886,  0.9204, -2.5826, -0.7704, -1.4521,  0.0217,  1.2625],
        [ 1.0596,  2.2700, -0.5311,  0.3357,  0.6043,  0.8335,  0.3125, -0.3519],
        [ 0.1616, -0.1158,  0.9844,  1.2782, -0.7955,  0.5378,  0.7150, -0.5199],
        [-0.1703, -0.3390,  1.4381,  0.3746, -1.1038, -0.5669,  0.4854, -0.3689]],
       requires_grad=True)
tensor([[4, 5, 0, 0, 0],
        [6, 3, 1, 7, 0]])
tensor([[[ 2.2568, -0.3080, -0.0466,  0.4633, -0.9516, -0.2778, -1.3498,
          -1.2884],
         [-0.3184,  0.9886,  0.9204, -2.5826, -0.7704, -1.4521,  0.0